endOfLine: "auto"
printWidth: 120
semi: false
singleQuote: true
trailingComma: "all"
overrides:
  - files:
      - "*.md"
      - "*.mdx"
    options:
      proseWrap: always
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      singleQuote: false
