#! /usr/bin/bash

endpoints="$(dirname "$0")/endpoint-schema-configs"

for file in $endpoints/*.json; do
    ./scripts/add-one-endpoint $file
done

echo "Done adding all endpoints. Make sure to update mint.json with the new pages."
