name: OpenAPI Specifications

on:
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run @apidevtools/swagger-cli validate on salad-cloud.json
        run: npx @apidevtools/swagger-cli validate ./api-specs/salad-cloud.json
      - name: Run @apidevtools/swagger-cli validate on salad-cloud-imds.json
        run: npx @apidevtools/swagger-cli validate ./api-specs/salad-cloud-imds.json
