name: OpenAPI Specifications

on:
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate All API Specs
        run: .github/scripts/validate-all-workflows.sh
