name: Spellcheck

on:
  pull_request:

jobs:
  spellcheck:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install Extra Dictionaries
        run: npm install
      - name: Do spellcheck
        uses: streetsidesoftware/cspell-action@v8
        with:
          files: "**/*.{md,mdx}"
          suggestions: true
