name: Spellcheck

on:
  pull_request:

jobs:
  spellcheck:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run swagger-cli (salad-cloud.json)
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.{md,mdx}"
